version: "3.9"
services:
  proxy:
    image: envoyproxy/envoy:v1.25.2
    ports:
      - 80:80
      - 443:443
      - 8443:8443
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml

  idp:
    image: quay.io/keycloak/keycloak:21.1
    command: start
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}

      KC_HOSTNAME_ADMIN_URL: https://localhost:8443/auth
      KC_HOSTNAME_URL: https://localhost/auth

      KC_HTTP_RELATIVE_PATH: /auth
      KC_HOSTNAME_STRICT: 'false'
      KC_PROXY: edge

      KC_HEALTH_ENABLED: 'true'
    depends_on:
      - postgres
    volumes:
     - 'mysql_data:/var/lib/mysql'

  postgres:
    image: postgres:15.3-bullseye
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'

  mysql:
   image: mysql:8.0.32
   command: --default-authentication-plugin=mysql_native_password
   restart: always
   environment:
     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
     MYSQL_DATABASE: ${MySQL_DB}
     MYSQL_USER: ${MySQL_Username}
     MYSQL_PASSWORD: ${MySQL_Password}
   ports:
     - '3306:3306'
   expose:
     - '3306'
   volumes:
     - 'mysql_data:/var/lib/mysql'

  auth_service:
    # image: bignya/auth
    build:
      context: ./src/auth_service
      dockerfile: ./Dockerfile
    environment:
      SERVER_URL: ${SERVER_URL}
      REALM: ${REALM}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      AUTHORIZATION_URL: ${AUTHORIZATION_URL}
      TOKEN_URL: ${TOKEN_URL}
    depends_on:
      - idp

  llm_service:
    # image: bignya/llm_service
    build:
      context: ./src/llm_service
      dockerfile: ./Dockerfile
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      AUTH_SVC_ADDRESS: ${AUTH_SVC_ADDRESS}
      AUTHORIZATION_URL: ${AUTHORIZATION_URL}
      TOKEN_URL: ${TOKEN_URL}
      MySQL_HOST: ${MySQL_HOST}
      MySQL_Username: ${MySQL_Username}
      MySQL_Password: ${MySQL_Password}
      MySQL_DB: ${MySQL_DB}
    depends_on:
      - mysql
      - idp
      - auth_service

  chat_service:
    # image: bignya/llm_service
    build:
      context: ./src/chat_service
      dockerfile: ./Dockerfile
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      AUTH_SVC_ADDRESS: ${AUTH_SVC_ADDRESS}
      AUTHORIZATION_URL: ${AUTHORIZATION_URL}
      TOKEN_URL: ${TOKEN_URL}
      MySQL_HOST: ${MySQL_HOST}
      MySQL_Username: ${MySQL_Username}
      MySQL_Password: ${MySQL_Password}
      MySQL_DB: ${MySQL_DB}
    depends_on:
      - mysql
      - idp
      - auth_service

volumes:
  mysql_data:
    driver: local
  postgres_data:
    driver: local